3.Pandas

In [1]:
# b
import pandas as pd
df = pd.read_csv("../data/Homework 0 Data/Salaries.csv")
df

yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
...       ...    ...  ...        ...       ...
25570    2015    WAS   NL  treinbl01    512800
25571    2015    WAS   NL  ugglada01    507500
25572    2015    WAS   NL  werthja01  21000000
25573    2015    WAS   NL  zimmejo02  16500000
25574    2015    WAS   NL  zimmery01  14000000

[25575 rows x 5 columns]

In [2]:
# c
df1 = pd.read_csv("../data/Homework 0 Data/Salaries.csv", header=0, index_col=3, skiprows=[1])
df1

yearID teamID lgID    salary
playerID                               
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
chambch01    1985    ATL   NL    800000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25574 rows x 4 columns]

In [3]:
# d
df[(df['teamID'] =='HOU') | (df['teamID'] =='ATL') & (df['salary']>1000000)]['playerID']

10       hornebo01
15       murphda05
20       suttebr01
202      ashbyal01
203       basske01
           ...    
25055    singljo02
25056     sippto01
25057    springe01
25058    thatcjo01
25059    valbulu01
Name: playerID, Length: 1178, dtype: object

In [41]:
# e
data_e = df[df['teamID'] =='ATL'].describe()
data_e

yearID        salary
count   886.000000  8.860000e+02
mean   1999.708804  2.206239e+06
std       8.775471  3.432673e+06
min    1985.000000  6.000000e+04
25%    1992.000000  3.000000e+05
50%    1999.000000  6.000000e+05
75%    2007.000000  2.390625e+06
max    2015.000000  1.606180e+07

In [5]:
# f
data_dic = dict()
data_dic['yearID'] = []
data_dic['teamID'] = []
data_dic['lgID'] = []
data_dic['playerID'] = []
data_dic['salary'] = []

for id, row in df.iterrows():
    data_dic['yearID'].append(row['yearID'])
    data_dic['teamID'].append(row['teamID'])
    data_dic['lgID'].append(row['lgID'])
    data_dic['playerID'].append(row['playerID'])
    data_dic['salary'].append(row['salary'])

# print(data_dic)

data_dic2 = df.to_dict()

In [42]:
# g
import numpy as np
input = np.array(data_e).reshape(2,8)
df2 = pd.DataFrame(np.array(input), columns=['a','b','c','d','e','f','g','h'])
# df2 = pd.DataFrame(data_e)
df2

a         b            c             d            e             f  \
0   886.0     886.0  1999.708804  2.206239e+06     8.775471  3.432673e+06   
1  1992.0  300000.0  1999.000000  6.000000e+05  2007.000000  2.390625e+06   

        g           h  
0  1985.0     60000.0  
1  2015.0  16061802.0

4.Numpy

In [71]:
# a
n = np.array([[1,2],[3,4],[5,6]])
n

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
# b
print(n.ndim, n.shape, n.size, n.dtype, n.itemsize, n.data)

2 (3, 2) 6 int64 8 <memory at 0x7f8b52e16790>


In [73]:
# c
np.reshape(n, [1,6])

array([[1, 2, 3, 4, 5, 6]])

In [74]:
print(n)
n.flatten()


[[1 2]
 [3 4]
 [5 6]]


array([1, 2, 3, 4, 5, 6])

In [76]:
# d
print(n[1:, :1])
print(n[1:2, 0:1]) # [left, right)

[[3]
 [5]]
[[3]]


In [87]:
# e
print(n.argmin(axis=1)) # index array of min value in given axis
print(n.argmax())
print(n.min(), n.max(axis=0))
print(n.mean(), n.max(), n.std())
print(n.dot(np.array([1,2])))
print(np.sqrt(n))
print(np.abs(n))
print(np.exp(n))
print(np.sin(n))
print(np.mod(n,2))

[0 0 0]
5
1 [5 6]
3.5 6 1.707825127659933
[ 5 11 17]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
[[1 2]
 [3 4]
 [5 6]]
[[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]
[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]
[[1 0]
 [1 0]
 [1 0]]


In [ ]:
# f
